### ISSUE TITLE
bug and puzzles with gh60's kicad sch file

### ISSUE THREAD

**Issue by 243750496** [komar007/gh60#28]
Q1:why setting up an no-using page(led.sch)
![led no use](https://user-images.githubusercontent.com/6311930/33321192-cb887b48-d47f-11e7-8d3e-a9b755b97423.png)

Q2:and there is a bug here
![bug](https://user-images.githubusercontent.com/6311930/33321114-6fcf4b42-d47f-11e7-8d6b-f4b1666661f0.png)

Q3:why you draw something like P11-15 with no line connect it?same as led part(in led.sch)
![why setting up these](https://user-images.githubusercontent.com/6311930/33321335-5128689e-d480-11e7-9b73-6ba5e1e696d7.png)

btw:i use gh60-revC_plain

**Comment by TweetyDaBird** [comment]
Q1: It's very clearly used for the backligth LED's...
Q2: Not a bug, just KiCad's way of saying it doesn't know if GND has power or not (useful only if you are running a simulation)
Q3: They are pulled out to the edge of the board, most likely for expansion...

This should be closed...

**Comment by komar007** [comment]
Well, it looks like I overlooked this issue 3 years ago:D
Thanks @TweetyDaBird, I think my answers would be exactly the same;)
